import {describe,it,expect,vi} from 'vitest';
import {forwardHostedRequest} from './hostedProxy.server';
import {decodeJwt} from 'jose';
const config={issuer:'https://identity.example.invalid',authorizationEndpoint:'https://identity.example.invalid/authorize',tokenEndpoint:'https://identity.example.invalid/token',jwksUri:'https://identity.example.invalid/jwks',allowedHosts:['identity.example.invalid'],resource:'https://api.example.invalid/external-booking-api',frontendOrigin:'https://rent.example.invalid',clientId:'hosted-customer',clientSecret:'synthetic-only',cookieKey:Buffer.alloc(32,4).toString('base64url'),bridgeKey:Buffer.alloc(32,5).toString('base64url')};
const session={issuer:config.issuer,subject:'renter',clientId:config.clientId,accessToken:'synthetic-test-token',expiresAt:Date.now()+60000,csrf:'synthetic-csrf',profile:{email:'verified@example.invalid',emailVerified:true,name:'Synthetic Renter'}};
const quote='10000000-0000-4000-8000-000000000008';
describe('customer same-origin backend bridge',()=>{
 it('starts only explicit nonce recovery and allows only a pending exact first-party renewal landing',async()=>{
  const nonce='a'.repeat(43),path='customer-handoffs/'+nonce+'/grant-renewals';
  const result={api_version:'v1',source_checked_at:new Date().toISOString(),renewal_id:quote,state:'authorization_required',customer_url:config.frontendOrigin+'/agent/authorization/'+quote,expires_at:new Date(Date.now()+60000).toISOString()};
  const transport=vi.fn(async(url:URL,init:RequestInit)=>{expect(url.pathname).toBe('/external-booking-api/v1/'+path);expect(JSON.parse(init.body as string)).toEqual({action:'continue'});return Response.json(result,{status:201});});
  expect((await forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf,action:'continue'},config.frontendOrigin,transport as any)).body).toEqual(result);
  for(const patch of [{customer_url:'https://evil.example/agent/authorization/'+quote},{customer_url:result.customer_url+'?token=private'},{customer_url:config.frontendOrigin+'/agent/authorization/10000000-0000-4000-8000-000000000009'},{state:'authorized',grant_id:quote},{expires_at:'2000-01-01T00:00:00Z'}])await expect(forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf,action:'continue'},config.frontendOrigin,(async()=>Response.json({...result,...patch},{status:201})) as any)).rejects.toThrow();
  for(const input of [{csrf:'wrong',action:'continue'},{csrf:session.csrf,action:'continue',grant_id:quote}])await expect(forwardHostedRequest(config,session,'POST',path,input,config.frontendOrigin,transport as any)).rejects.toThrow();
  await expect(forwardHostedRequest(config,session,'GET',path,null,null,transport as any)).rejects.toThrow();
 });
 it.each(['identity','checkout'])('creates only the explicitly chosen customer-owned %s handoff with fresh proof',async action=>{
  const path='customers/rental-requests/SYNTHETIC-REQUEST/'+action+'-handoff';
  const output={api_version:'v1',source_checked_at:new Date().toISOString(),customer_url:config.frontendOrigin+'/agent/handoff/'+'a'.repeat(43),expires_at:new Date(Date.now()+60000).toISOString(),state:action==='identity'?'pending_documents':'pending_payment',next_action:action==='identity'?'verify_identity':'hosted_checkout'};
  const transport=vi.fn(async(url:URL,init:RequestInit)=>{expect(url.pathname).toBe('/external-booking-api/v1/'+path);expect(JSON.parse(init.body as string)).toEqual({action:'continue'});expect(decodeJwt((init.headers as any)['X-Exotiq-Hosted-Proof']).path).toBe(url.pathname);return Response.json(output);});
  expect((await forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf,action:'continue'},config.frontendOrigin,transport as any)).body).toEqual(output);
  await expect(forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf,action:'continue',customer_id:quote},config.frontendOrigin,transport as any)).rejects.toThrow();
  await expect(forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf,action:'continue'},config.frontendOrigin,(async()=>Response.json({...output,customer_url:'https://checkout.stripe.com/private'})) as any)).rejects.toThrow();
  await expect(forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf,action:'continue'},config.frontendOrigin,(async()=>Response.json({...output,expires_at:'2000-01-01T00:00:00Z'})) as any)).rejects.toThrow();
 });
 it('signs the real customer-owned status path and refuses raw provider/private output',async()=>{
  const path='customers/rental-requests/SYNTHETIC-REQUEST';
  const body={api_version:'v1',source_checked_at:new Date().toISOString(),ref:'SYNTHETIC-REQUEST',operator_id:quote,operator_name:'Synthetic operator',vehicle_name:'Synthetic car',status:'pending_payment',next_action:'await_reconciliation',hold_expires_at:null,payment_due_at:null};
  const transport=vi.fn(async(url:URL,init:RequestInit)=>{expect(url.pathname).toBe('/external-booking-api/v1/'+path);expect(decodeJwt((init.headers as any)['X-Exotiq-Hosted-Proof']).path).toBe(url.pathname);return Response.json(body);});
  expect((await forwardHostedRequest(config,session,'GET',path,null,null,transport as any)).body).toEqual(body);
  await expect(forwardHostedRequest(config,session,'GET',path,null,null,(async()=>Response.json({...body,provider_url:'https://checkout.stripe.com/private'})) as any)).rejects.toThrow();
  expect(await forwardHostedRequest(config,session,'GET',path,null,null,(async()=>Response.json({message:'private other customer'},{status:404})) as any)).toEqual({status:404,body:{code:'customer_status_unavailable'}});
  await expect(forwardHostedRequest(config,session,'POST',path,{csrf:session.csrf},config.frontendOrigin,transport as any)).rejects.toThrow();
 });
 it('denies CSRF and path bypass without making an upstream request',async()=>{const transport=vi.fn();await expect(forwardHostedRequest(config,session,'POST',`quotes/${quote}/consents`,{csrf:'wrong'},config.frontendOrigin,transport)).rejects.toThrow();await expect(forwardHostedRequest(config,session,'GET','admin',null,config.frontendOrigin,transport)).rejects.toThrow();expect(transport).not.toHaveBeenCalled();});
 it('keeps verified identity in signed proof and forwards only onboarding contact fields',async()=>{const transport=vi.fn(async(_url,options)=>{const body=JSON.parse(options.body);expect(body).toEqual({operator_id:quote,full_name:'Contact Name',phone:'+15555550123',consented:true});expect(options.headers.authorization).toBe('Bearer synthetic-test-token');const proof=decodeJwt(options.headers['X-Exotiq-Hosted-Proof']);expect(proof.profile_email).toBe('verified@example.invalid');expect(proof.profile_email_verified).toBe(true);expect(proof.provider_subject).toBe(session.subject);expect(options.cache).toBe('no-store');return new Response(JSON.stringify({state:'linked'}),{headers:{'content-type':'application/json'}});});const response=await forwardHostedRequest(config,session,'POST','customers/operator-links',{csrf:session.csrf,operator_id:quote,full_name:'Contact Name',phone:'+15555550123',consented:true,email:'attacker@example.invalid',email_verified:true,customer_id:quote,subject:'attacker'},config.frontendOrigin,transport as any);expect(response.status).toBe(200);expect(JSON.stringify(response)).not.toContain(session.accessToken);});
 it.each(['confirmation_token','access_token','consent_receipt_id','driver_license','card_number'])('refuses a backend secret field %s',async(field)=>{const transport=async()=>new Response(JSON.stringify({nested:{[field]:'secret'}}),{headers:{'content-type':'application/json'}});await expect(forwardHostedRequest(config,session,'GET',`quotes/${quote}`,null,config.frontendOrigin,transport as any)).rejects.toThrow();});
 it('rejects expired session, cross-origin write and unverified onboarding identity',async()=>{const transport=vi.fn();await expect(forwardHostedRequest(config,{...session,expiresAt:0},'GET',`quotes/${quote}`,null,config.frontendOrigin,transport)).rejects.toThrow();await expect(forwardHostedRequest(config,session,'POST',`quotes/${quote}/consents`,{csrf:session.csrf},'https://evil.example',transport)).rejects.toThrow();await expect(forwardHostedRequest(config,{...session,profile:{...session.profile,emailVerified:false}},'POST','customers/operator-links',{csrf:session.csrf,operator_id:quote},config.frontendOrigin,transport)).rejects.toThrow();expect(transport).not.toHaveBeenCalled();});
});
