import {describe,it,expect,vi} from 'vitest';
import {forwardHostedRequest} from './hostedProxy.server';
const config={issuer:'https://identity.example.invalid',authorizationEndpoint:'https://identity.example.invalid/authorize',tokenEndpoint:'https://identity.example.invalid/token',jwksUri:'https://identity.example.invalid/jwks',allowedHosts:['identity.example.invalid'],resource:'https://api.example.invalid/external-booking-api',frontendOrigin:'https://rent.example.invalid',clientId:'hosted-customer',clientSecret:'synthetic-only',cookieKey:Buffer.alloc(32,4).toString('base64url'),bridgeKey:Buffer.alloc(32,5).toString('base64url')};
const session={issuer:config.issuer,subject:'renter',clientId:config.clientId,accessToken:'synthetic-test-token',expiresAt:Date.now()+60000,csrf:'synthetic-csrf',profile:{email:'verified@example.invalid',emailVerified:true,name:'Synthetic Renter'}};
const quote='10000000-0000-4000-8000-000000000008';
describe('customer same-origin backend bridge',()=>{
 it('denies CSRF and path bypass without making an upstream request',async()=>{const transport=vi.fn();await expect(forwardHostedRequest(config,session,'POST',`quotes/${quote}/consents`,{csrf:'wrong'},config.frontendOrigin,transport)).rejects.toThrow();await expect(forwardHostedRequest(config,session,'GET','admin',null,config.frontendOrigin,transport)).rejects.toThrow();expect(transport).not.toHaveBeenCalled();});
 it('keeps tokens server-side, forwards proof and takes onboarding email from authenticated profile',async()=>{const transport=vi.fn(async(_url,options)=>{const body=JSON.parse(options.body);expect(body.email).toBe('verified@example.invalid');expect(body.email_verified).toBe(true);expect(body.csrf).toBeUndefined();expect(options.headers.authorization).toBe('Bearer synthetic-test-token');expect(options.headers['X-Exotiq-Hosted-Proof']).toBeTruthy();expect(options.cache).toBe('no-store');return new Response(JSON.stringify({state:'linked'}),{headers:{'content-type':'application/json'}});});const response=await forwardHostedRequest(config,session,'POST','customers/operator-links',{csrf:session.csrf,operator_id:quote,email:'attacker@example.invalid'},config.frontendOrigin,transport as any);expect(response.status).toBe(200);expect(JSON.stringify(response)).not.toContain(session.accessToken);});
 it.each(['confirmation_token','access_token','consent_receipt_id','driver_license','card_number'])('refuses a backend secret field %s',async(field)=>{const transport=async()=>new Response(JSON.stringify({nested:{[field]:'secret'}}),{headers:{'content-type':'application/json'}});await expect(forwardHostedRequest(config,session,'GET',`quotes/${quote}`,null,config.frontendOrigin,transport as any)).rejects.toThrow();});
 it('rejects expired session, cross-origin write and unverified onboarding identity',async()=>{const transport=vi.fn();await expect(forwardHostedRequest(config,{...session,expiresAt:0},'GET',`quotes/${quote}`,null,config.frontendOrigin,transport)).rejects.toThrow();await expect(forwardHostedRequest(config,session,'POST',`quotes/${quote}/consents`,{csrf:session.csrf},'https://evil.example',transport)).rejects.toThrow();await expect(forwardHostedRequest(config,{...session,profile:{...session.profile,emailVerified:false}},'POST','customers/operator-links',{csrf:session.csrf,operator_id:quote},config.frontendOrigin,transport)).rejects.toThrow();expect(transport).not.toHaveBeenCalled();});
});
