import type { BookingCart, ExtraSelection, Operator, PickupLocation, Vehicle } from './types';
import { calculateBookingTotals } from './totals';

export const mockOperators: Operator[] = [
  {
    id: 'team_desert_exotic_rentals',
    slug: 'desert-exotic-rentals',
    name: 'Desert Exotic Rentals',
    city: 'Scottsdale',
    state: 'AZ',
    phone: '+14805550142',
    logoUrl: '/images/logos/drive-exotiq-logo-white.png',
    timezone: 'America/Phoenix',
    platformFeePercent: 10,
    about:
      'Scottsdale’s concierge supercar fleet. Every car is detailed, inspected, and handed off in person — at our showroom or delivered to your resort.',
    policies: {
      minimumDriverAge: 25,
      freeCancellationHours: 72,
      milesIncludedPerDay: 'unlimited',
      fuelPolicy: 'Return with the same fuel level as pickup.',
      deliveryAvailable: true,
      deliveryNote: 'Concierge delivery within a 25-mile radius of Scottsdale.',
    },
  },
  {
    id: 'team_mile_high_exotics',
    slug: 'mile-high-exotics',
    name: 'Mile High Exotics',
    city: 'Denver',
    state: 'CO',
    phone: '+17205550177',
    logoUrl: '/images/logos/drive-exotiq-logo-white.png',
    timezone: 'America/Denver',
    platformFeePercent: 10,
    about:
      'Performance cars built for the front range — canyon runs, mountain passes, and city weekends. Route suggestions included with every rental.',
    policies: {
      minimumDriverAge: 25,
      freeCancellationHours: 72,
      milesIncludedPerDay: 200,
      fuelPolicy: 'Full-to-full. Premium fuel only.',
      deliveryAvailable: true,
      deliveryNote: 'Delivery available to Denver metro and DEN airport.',
    },
  },
  {
    id: 'team_vegas_supercar_collective',
    slug: 'vegas-supercar-collective',
    name: 'Vegas Supercar Collective',
    city: 'Las Vegas',
    state: 'NV',
    phone: '+17025550119',
    logoUrl: '/images/logos/drive-exotiq-logo-white.png',
    timezone: 'America/Los_Angeles',
    platformFeePercent: 10,
    about:
      'Flagship grand tourers and chauffeur-grade luxury on the Strip. Valet handoff at any major resort, day or night.',
    policies: {
      minimumDriverAge: 30,
      freeCancellationHours: 72,
      milesIncludedPerDay: 150,
      fuelPolicy: 'Return with the same fuel level as pickup.',
      deliveryAvailable: true,
      deliveryNote: 'Valet handoff at all major Strip resorts, 24/7.',
    },
  },
];

export const mockOperator = mockOperators[0];

const scottsdaleShowroom: PickupLocation = {
  id: 'loc_scottsdale_showroom',
  name: 'Scottsdale showroom',
  address: '7001 N Scottsdale Rd',
  city: 'Scottsdale',
  state: 'AZ',
  phone: mockOperators[0].phone,
};

const denverShowroom: PickupLocation = {
  id: 'loc_denver_showroom',
  name: 'Denver showroom',
  address: '2500 Walnut St',
  city: 'Denver',
  state: 'CO',
  phone: mockOperators[1].phone,
};

const vegasGarage: PickupLocation = {
  id: 'loc_vegas_garage',
  name: 'Strip-side private garage',
  address: '3720 S Las Vegas Blvd',
  city: 'Las Vegas',
  state: 'NV',
  phone: mockOperators[2].phone,
};

export const mockVehicles: Vehicle[] = [
  // --- Desert Exotic Rentals (Scottsdale, AZ) ---
  {
    id: 'veh_mclaren_750s_spider',
    slug: 'mclaren-750s-spider',
    operatorId: mockOperators[0].id,
    name: '2024 McLaren 750S Spider',
    shortName: 'McLaren 750S',
    year: 2024,
    make: 'McLaren',
    model: '750S Spider',
    dailyRateCents: 119900,
    minRentalDays: 3,
    securityDepositCents: 250000,
    photos: ['/images/vehicles/mclaren-750s.png', '/images/vehicles/hero-exotic-car.png', '/images/app/app-detail.png'],
    heroImage: '/images/vehicles/mclaren-750s.png',
    specs: { zeroToSixty: '2.7s', power: '740 hp', engine: 'V8 twin-turbo', transmission: '7-speed SSG' },
    footnote: '3-day minimum · Unlimited miles included',
    pickupLocation: scottsdaleShowroom,
    unavailableRanges: [{ start: '2026-06-20', end: '2026-06-24' }],
  },
  {
    id: 'veh_lamborghini_huracan_evo',
    slug: 'lamborghini-huracan-evo',
    operatorId: mockOperators[0].id,
    name: '2023 Lamborghini Huracán EVO',
    shortName: 'Huracán EVO',
    year: 2023,
    make: 'Lamborghini',
    model: 'Huracán EVO',
    dailyRateCents: 99900,
    minRentalDays: 2,
    securityDepositCents: 250000,
    photos: ['/images/vehicles/lamborghini-huracan.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/lamborghini-huracan.png',
    specs: { zeroToSixty: '2.9s', power: '631 hp', engine: 'V10 naturally aspirated', transmission: '7-speed dual-clutch' },
    footnote: '2-day minimum · 150 miles/day included',
    pickupLocation: scottsdaleShowroom,
    unavailableRanges: [{ start: '2026-06-05', end: '2026-06-08' }],
  },
  {
    id: 'veh_ferrari_296_gtb',
    slug: 'ferrari-296-gtb',
    operatorId: mockOperators[0].id,
    name: '2023 Ferrari 296 GTB',
    shortName: 'Ferrari 296',
    year: 2023,
    make: 'Ferrari',
    model: '296 GTB',
    dailyRateCents: 114900,
    minRentalDays: 3,
    securityDepositCents: 250000,
    photos: ['/images/vehicles/ferrari-296-gtb.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/ferrari-296-gtb.png',
    specs: { zeroToSixty: '2.9s', power: '819 hp', engine: 'V6 hybrid twin-turbo', transmission: '8-speed F1 DCT' },
    footnote: '3-day minimum · Concierge handoff available',
    pickupLocation: scottsdaleShowroom,
    unavailableRanges: [{ start: '2026-06-26', end: '2026-06-30' }],
  },
  {
    id: 'veh_lamborghini_urus',
    slug: 'lamborghini-urus',
    operatorId: mockOperators[0].id,
    name: '2024 Lamborghini Urus S',
    shortName: 'Urus S',
    year: 2024,
    make: 'Lamborghini',
    model: 'Urus S',
    dailyRateCents: 74900,
    minRentalDays: 1,
    securityDepositCents: 150000,
    photos: ['/images/vehicles/lamborghini-urus.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/lamborghini-urus.png',
    specs: { zeroToSixty: '3.5s', power: '657 hp', engine: 'V8 twin-turbo', transmission: '8-speed automatic' },
    footnote: 'No minimum · Seats five with luggage',
    pickupLocation: scottsdaleShowroom,
  },

  // --- Mile High Exotics (Denver, CO) ---
  {
    id: 'veh_porsche_911_gt3_rs',
    slug: 'porsche-911-gt3-rs',
    operatorId: mockOperators[1].id,
    name: '2024 Porsche 911 GT3 RS',
    shortName: '911 GT3 RS',
    year: 2024,
    make: 'Porsche',
    model: '911 GT3 RS',
    dailyRateCents: 89900,
    minRentalDays: 2,
    securityDepositCents: 250000,
    photos: ['/images/vehicles/porsche-911-gt3rs.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/porsche-911-gt3rs.png',
    specs: { zeroToSixty: '3.0s', power: '518 hp', engine: 'Flat-six naturally aspirated', transmission: '7-speed PDK' },
    footnote: '2-day minimum · Track-day add-on available',
    pickupLocation: denverShowroom,
    unavailableRanges: [{ start: '2026-06-12', end: '2026-06-15' }],
  },
  {
    id: 'veh_mercedes_amg_gt63',
    slug: 'mercedes-amg-gt63',
    operatorId: mockOperators[1].id,
    name: '2023 Mercedes-AMG GT 63 S',
    shortName: 'AMG GT 63',
    year: 2023,
    make: 'Mercedes-AMG',
    model: 'GT 63 S',
    dailyRateCents: 64900,
    minRentalDays: 2,
    securityDepositCents: 150000,
    photos: ['/images/vehicles/mercedes-amg-gt63.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/mercedes-amg-gt63.png',
    specs: { zeroToSixty: '3.1s', power: '630 hp', engine: 'V8 biturbo', transmission: '9-speed MCT' },
    footnote: '2-day minimum · 200 miles/day included',
    pickupLocation: denverShowroom,
  },
  {
    id: 'veh_range_rover_sv',
    slug: 'range-rover-sv',
    operatorId: mockOperators[1].id,
    name: '2024 Range Rover SV',
    shortName: 'Range Rover SV',
    year: 2024,
    make: 'Land Rover',
    model: 'Range Rover SV',
    dailyRateCents: 54900,
    minRentalDays: 2,
    securityDepositCents: 100000,
    photos: ['/images/vehicles/range-rover-sv.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/range-rover-sv.png',
    specs: { zeroToSixty: '4.3s', power: '606 hp', engine: 'V8 twin-turbo', transmission: '8-speed automatic' },
    footnote: '2-day minimum · Mountain-ready luxury',
    pickupLocation: denverShowroom,
    unavailableRanges: [{ start: '2026-06-01', end: '2026-06-03' }],
  },
  {
    id: 'veh_bmw_m4_competition',
    slug: 'bmw-m4-competition',
    operatorId: mockOperators[1].id,
    name: '2024 BMW M4 Competition',
    shortName: 'M4 Competition',
    year: 2024,
    make: 'BMW',
    model: 'M4 Competition',
    dailyRateCents: 39900,
    minRentalDays: 1,
    securityDepositCents: 75000,
    photos: ['/images/vehicles/bmw-m4-competition.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/bmw-m4-competition.png',
    specs: { zeroToSixty: '3.4s', power: '503 hp', engine: 'Inline-six twin-turbo', transmission: '8-speed automatic' },
    footnote: 'No minimum · Great first exotic weekend',
    pickupLocation: denverShowroom,
  },

  // --- Vegas Supercar Collective (Las Vegas, NV) ---
  {
    id: 'veh_rolls_royce_ghost',
    slug: 'rolls-royce-ghost',
    operatorId: mockOperators[2].id,
    name: '2024 Rolls-Royce Ghost',
    shortName: 'Ghost',
    year: 2024,
    make: 'Rolls-Royce',
    model: 'Ghost',
    dailyRateCents: 149900,
    minRentalDays: 2,
    securityDepositCents: 500000,
    photos: ['/images/vehicles/rolls-royce-ghost.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/rolls-royce-ghost.png',
    specs: { zeroToSixty: '4.6s', power: '563 hp', engine: 'V12 twin-turbo', transmission: '8-speed automatic' },
    footnote: '2-day minimum · Chauffeur option available',
    pickupLocation: vegasGarage,
    unavailableRanges: [{ start: '2026-06-18', end: '2026-06-21' }],
  },
  {
    id: 'veh_bentley_continental_gt',
    slug: 'bentley-continental-gt',
    operatorId: mockOperators[2].id,
    name: '2023 Bentley Continental GT',
    shortName: 'Continental GT',
    year: 2023,
    make: 'Bentley',
    model: 'Continental GT',
    dailyRateCents: 89900,
    minRentalDays: 2,
    securityDepositCents: 250000,
    photos: ['/images/vehicles/bentley-continental-gt.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/bentley-continental-gt.png',
    specs: { zeroToSixty: '3.6s', power: '650 hp', engine: 'W12 twin-turbo', transmission: '8-speed dual-clutch' },
    footnote: '2-day minimum · 150 miles/day included',
    pickupLocation: vegasGarage,
  },
  {
    // Hidden vehicle example: in the fleet but not marketplace-visible (roadmap Task 2.1).
    id: 'veh_aston_martin_db12',
    slug: 'aston-martin-db12',
    operatorId: mockOperators[2].id,
    name: '2024 Aston Martin DB12',
    shortName: 'DB12',
    year: 2024,
    make: 'Aston Martin',
    model: 'DB12',
    dailyRateCents: 99900,
    minRentalDays: 2,
    securityDepositCents: 250000,
    photos: ['/images/vehicles/aston-martin-db12.png', '/images/vehicles/hero-exotic-car.png'],
    heroImage: '/images/vehicles/aston-martin-db12.png',
    specs: { zeroToSixty: '3.5s', power: '671 hp', engine: 'V8 twin-turbo', transmission: '8-speed automatic' },
    footnote: '2-day minimum · In detailing — not yet listed',
    pickupLocation: vegasGarage,
    hidden: true,
  },
];

export const mockVehicle = mockVehicles[0];

export const curatedExtras: ExtraSelection[] = [
  { id: 'delivery', name: 'Concierge delivery', description: 'We bring it to your hotel · 25-mile radius', priceCents: 15000, unit: 'flat', defaultSelected: true },
  { id: 'driver', name: 'Additional driver', description: 'Second verified driver on the rental.', priceCents: 4500, unit: 'day' },
  { id: 'photo', name: 'Photo package', description: '90-minute shoot · 30 edited images.', priceCents: 40000, unit: 'flat' },
  { id: 'late-return', name: 'Late return', description: 'Until 6 PM on the final day.', priceCents: 7500, unit: 'flat' },
];

export function createInitialCart(overrides: { operator?: Operator; vehicle?: Vehicle } = {}): BookingCart {
  const vehicle = overrides.vehicle ?? mockVehicle;
  const operator = overrides.operator ?? mockOperators.find((team) => team.id === vehicle.operatorId) ?? mockOperator;
  const selectedExtras = curatedExtras.filter((extra) => extra.defaultSelected);
  const dates = { start: '2026-06-14', end: '2026-06-17' };
  const protection = 'premium' as const;

  return {
    operator,
    vehicle,
    dates,
    pickupTime: '10:00 AM',
    driver: {
      name: 'Gregory James',
      dob: '1985-06-14',
      phone: '+13035550184',
      email: 'gregory@example.com',
    },
    extras: selectedExtras,
    protection,
    totals: calculateBookingTotals({
      dailyRateCents: vehicle.dailyRateCents,
      startDate: dates.start,
      endDate: dates.end,
      extras: selectedExtras,
      protection,
      operatorTaxRate: 0.078,
      platformFeeRate: (operator.platformFeePercent ?? 10) / 100,
      depositHoldCents: vehicle.securityDepositCents,
    }),
  };
}
